# Limit memory on RAM
maxmemory 256mb

# Least recently used: When memory reaches 256MB, Redis will delete the key with the shortest TTL (Time To Live: the lifetime of a key, in seconds) and the least used
maxmemory-policy volatile-lru

# Enable persistence (RDB) to save data
# Save after 900s if there is only 1 change
save 900 1

# Save after 300s if there is only 10 changes
save 300 10

 # Save after 60s if there is only 10000 changes
save 60 10000

dir /data